IdentityServer4.Admin/src/Skoruba.IdentityServer4.Admin.UI/Areas/AdminUI/Controllers/LogController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Log;
using Skoruba.IdentityServer4.Admin.BusinessLogic.Services.Interfaces;
using Skoruba.IdentityServer4.Admin.UI.Configuration.Constants;

namespace Skoruba.IdentityServer4.Admin.UI.Areas.AdminUI.Controllers
{
    [Authorize(Policy = AuthorizationConsts.AdministrationPolicy)]
    [Area(CommonConsts.AdminUIArea)]
    public class LogController : BaseController
    {
        private readonly ILogService _logService;
        private readonly IAuditLogService _auditLogService;

        public LogController(ILogService logService,
            ILogger<ConfigurationController> logger,
            IAuditLogService auditLogService) : base(logger)
        {
            _logService = logService;
            _auditLogService = auditLogService;
        }

        [HttpGet]
        public async Task<IActionResult> ErrorsLog(int? page, string search)
        {
            ViewBag.Search = search;
            var logs = await _logService.GetLogsAsync(search, page ?? 1);

            return View(logs);
        }

        [HttpGet]
        public async Task<IActionResult> AuditLog([FromQuery]AuditLogFilterDto filters)
        {
            ViewBag.SubjectIdentifier = filters.SubjectIdentifier;
            ViewBag.SubjectName = filters.SubjectName;
            ViewBag.Event = filters.Event;
            ViewBag.Source = filters.Source;
            ViewBag.Category = filters.Category;

            var logs = await _auditLogService.GetAsync(filters);

            return View(logs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteLogs(LogsDto log)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(ErrorsLog), log);
            }
            
            await _logService.DeleteLogsOlderThanAsync(log.DeleteOlderThan.Value);

            return RedirectToAction(nameof(ErrorsLog));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAuditLogs(AuditLogsDto log)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(AuditLog), log);
            }

            await _auditLogService.DeleteLogsOlderThanAsync(log.DeleteOlderThan.Value);

            return RedirectToAction(nameof(AuditLog));
        }
    }
}

IdentityServer4.Admin/src/Skoruba.IdentityServer4.Admin.UI/Areas/AdminUI/Views/Log/AuditLog.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Shared.Dtos.Common
@using Skoruba.IdentityServer4.Admin.UI.Configuration.Constants
@model Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Log.AuditLogsDto
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Audit Log"];
}

<div class="audit-log-container">

    <div class="row">
        <div class="col-12 mb-3 text-center mt-1">
            <h2><span class="oi oi-eye" title="Audit Logging" aria-hidden="true"></span> @ViewData["Title"]</h2>
        </div>
    </div>

    <form asp-area="@CommonConsts.AdminUIArea" class="audit-log-form" asp-controller="Log" asp-action="DeleteAuditLogs">
        <div class="d-flex flex-row mt-3 justify-content-end mb-3">
            <div class="p-2">
                <a href="#" class="btn btn-danger audit-log-delete-button">
                    @Localizer["Delete logs older than"]
                </a>
            </div>
            <div class="p-1">
                <!--Date Picker-->
                <div class="datepicker input-group date">
                    <input asp-for="DeleteOlderThan" autocomplete="off" type="text" class="form-control">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="deleteLogsModal" tabindex="-1" role="dialog" aria-labelledby="deleteLogsModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="deletePersistedGrantsModalLabel">@Localizer["Warning"]</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        @Localizer["Are you sure?"]
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">@Localizer["Yes - delete"]</button>
                        <button type="button" class="btn btn-outline-primary" data-dismiss="modal">@Localizer["No - close"]</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-12">
            <form asp-area="@CommonConsts.AdminUIArea" asp-controller="Log" asp-action="AuditLog" method="get">
                <div class="form-row">
                    <div class="col-2 mb-3">
                        <input name="subjectIdentifier" value="@ViewBag.SubjectIdentifier" type="text" placeholder="@Localizer["Subject Identifier"]" class="form-control" />
                    </div>
                    <div class="col-2 mb-3">
                        <input name="subjectName" value="@ViewBag.SubjectName" type="text" placeholder="@Localizer["Subject Name"]" class="form-control" />
                    </div>

                    <div class="col-3 mb-3">
                        <input name="event" value="@ViewBag.Event" type="text" placeholder="@Localizer["Event"]" class="form-control" />
                    </div>

                    <div class="col-3 mb-3">
                        <input name="source" value="@ViewBag.Source" type="text" placeholder="@Localizer["Source"]" class="form-control" />
                    </div>

                    <div class="col-2 mb-3">
                        <input name="category" value="@ViewBag.Category" type="text" placeholder="@Localizer["Category"]" class="form-control" />
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-12 mb-3">
                        <input type="submit" class="btn btn-primary" value="@Localizer["Search"]" />
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>@Localizer["Event"]</th>
                            <th>@Localizer["Source"]</th>
                            <th>@Localizer["Subject"]</th>
                            <th>@Localizer["Action"]</th>
                            <th>@Localizer["Created"]</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var auditLog in Model.Logs)
                        {
                            <tr>
                                <td><a href="#" data-error-id="@auditLog.Id" class="btn btn-primary btn-error-detail">@Localizer["Detail"]</a></td>
                                <td>@auditLog.Event</td>
                                <td>@auditLog.Source</td>
                                <td><button class="audit-subject-button btn btn-outline-primary" data-subject-name="@auditLog.SubjectName" data-subject-identifier="@auditLog.SubjectIdentifier" data-subject-type="@auditLog.SubjectType" data-subject-additional-data="@auditLog.SubjectAdditionalData">@auditLog.SubjectName - @Localizer["Show detail"] <i class="fa fa-eye"></i></button></td>
                                <td><button class="audit-action-button btn btn-outline-primary" data-action-title="@Localizer["Action"]" data-action="@auditLog.Action">@Localizer["Show detail"] <i class="fa fa-eye"></i></button></td>
                                <td>
                                    @auditLog.Created
                                </td>
                            </tr>
                            <tr class="row-error-detail d-none" data-error-id="@auditLog.Id">
                                <td colspan="6" data-error-json="@auditLog.Data"></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            @await Html.PartialAsync("Common/PagerDynamic", new Pager { Action = Url.Action("AuditLog", "Log", new { Area = CommonConsts.AdminUIArea }), PageSize = Model.PageSize, TotalCount = Model.TotalCount, EnableSearch = true, Search = ViewBag.Search })
        </div>
    </div>

    <div class="audit-modal modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="audit-modal-value"></div>
                </div>
            </div>
        </div>
    </div>
    </div>

IdentityServer4.Admin/src/Skoruba.IdentityServer4.Admin.UI/Areas/AdminUI/Views/Log/ErrorsLog.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Shared.Dtos.Common
@using Skoruba.IdentityServer4.Admin.UI.Configuration.Constants
@using Skoruba.IdentityServer4.Admin.UI.Helpers
@model Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Log.LogsDto
@inject IViewLocalizer Localizer

@{
    ViewBag.Title = Localizer["PageTitle"];
    Layout = "_Layout";
}

<div class="row">
    <div class="col-12 mb-3 text-center mt-1">
        <h2><span class="oi oi-bug" title="Error Logs" aria-hidden="true"></span> @Localizer["PageTitle"]</h2>
    </div>
</div>


<div class="col-12">
    <div asp-validation-summary="All" class="text-danger"></div>
</div>

<form asp-area="@CommonConsts.AdminUIArea" class="error-log-form" asp-controller="Log" asp-action="DeleteLogs">
    <div class="d-flex flex-row mt-3 justify-content-end mb-3">
        <div class="p-2">
            <a href="#" class="btn btn-danger error-log-delete-button">
                @Localizer["DeleteButton"]
            </a>
        </div>
        <div class="p-1">
            <!--Date Picker-->
            <div class="datepicker input-group date">
                <input asp-for="DeleteOlderThan" autocomplete="off" type="text" class="form-control">
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteLogsModal" tabindex="-1" role="dialog" aria-labelledby="deleteLogsModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="deletePersistedGrantsModalLabel">@Localizer["DeleteDialogTitle"]</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    @Localizer["DeleteDialogMessage"]
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">@Localizer["DeleteDialogYes"]</button>
                    <button type="button" class="btn btn-outline-primary" data-dismiss="modal">@Localizer["DeleteDialogNo"]</button>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-12">
        @await Html.PartialAsync("Common/Search", new Search { Action = "ErrorsLog", Controller = "Log" })
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th></th>
                        <th>@Localizer["TableLevel"]</th>
                        <th>@Localizer["TableLogged"]</th>
                        <th>@Localizer["TableMessage"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var log in Model.Logs)
                    {
                        <tr>
                            <td><a href="#" data-error-id="@log.Id" class="btn btn-primary btn-error-detail">@Localizer["TableShowDetail"]</a></td>
                            <td>@log.Level</td>
                            <td>
                                <span class="local-datetime" title="@log.TimeStamp" data-utc="@log.TimeStamp.GetEpochTicks()" data-toggle="tooltip" data-placement="top">
                                    @log.TimeStamp
                                </span>
                                <span class="oi oi-clock" title="@log.TimeStamp" data-toggle="tooltip" data-placement="top"></span>
                            </td>
                            <td>@log.Message</td>
                        </tr>
                        <tr class="row-error-detail d-none" data-error-id="@log.Id">
                            <td colspan="4" data-error-json="@log.LogEvent"></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        @await Html.PartialAsync("Common/Pager", new Pager { Action = "ErrorsLog", PageSize = Model.PageSize, TotalCount = Model.TotalCount, EnableSearch = true, Search = ViewBag.Search })
    </div>
</div>